### PR TITLE
Add page of causal video resources from PyMC community into the docs

### LINKED ISSUE #374: Add causal videos from PyMC / PyMC Labs community
Add a new page under the Knowledge Base which contains causal inference videos put out by the broad PyMC community. Existing videos would be:
* https://www.youtube.com/watch?v=0PQ8BQaDP04
* https://www.youtube.com/watch?v=b47wmTdcICE
* https://www.youtube.com/watch?v=QAzAFess1AA

### PR DESCRIPTION
**Pull request by ParthJohri**
# feat: Add causal videos from PyMC / PyMC Labs community [Issue No: 374](https://github.com/pymc-labs/CausalPy/issues/374)

## What type of PR:-
- [x] ✨ Enhancement
- [x] 📃 Documentation

## Description

1. Added the `causal_video_resources` page markdown file for the PyMC Labs Videos, used iframe to add the videos.
2. Tested if the UI is responsive or not in both light and dark mode.
3. Updated the `index.md` for the knowledge base to include the page link for the `causal_video_resources`.

## Screenshot & Screen recording

https://github.com/pymc-labs/CausalPy/assets/76129377/7305cb30-6a73-4c7c-a403-8c2e916219d6

link-check

----
📚 Documentation preview 📚: https://causalpy--379.org.readthedocs.build/en/379/

### CODE REVIEW

**Review by drbenvincent — CHANGES_REQUESTED** [review]
Great stuff. Thanks for this. Can I request a small change?

Remove the level 2 markdown header "PyMC Videos" and instead replace with Level 2 markdown headers with a short video title above each of the videos. Something like:
* Combining Bayes and Graph-based Causal Inference
* Bayesian Causal Modeling
* Guide to Causal Inference with PyMC

oh, and I think we may we well also add in the video from the home page as well seeing as that was pretty much a release announcement for CausalPy.

**Comment by ParthJohri** [comment]
@drbenvincent , I made the following changes, please let me know if any other change has to be made.

## Changes 

- [x] Removed level 2 pyVideos header.
- [x] Added level 2 headers for respective causal videos.
- [x] Added home page video of announcement for CausalPy in the causal video resources as well.

## Screenshots

change1
change2
change3
change4

**Comment by drbenvincent** [comment]
Excellent. Very minor thing, but can we change `What if Causal reasoning meets Bayesian Inference` to `What if? Causal reasoning meets Bayesian Inference`. Then we are good to merge :)

**Comment by ParthJohri** [comment]
@drbenvincent I have made the title change, let me know if any other change has to be made?

change5

**Comment by drbenvincent** [comment]
Thanks very much for your first contribution @ParthJohri!

If you have time, if relevant, I'd be interested to hear about any pain points in the process of contributing. For example, could the `CONTRIBUTING` doc be clearer etc, or did you run into any issues setting up the dev environment?

I'll slightly modify the PR title simply because that it what will appear in the auto generated release notes.

Thanks again!

**Review by drbenvincent — APPROVED** [review]

**Comment by ParthJohri** [comment]
> Thanks very much for your first contribution @ParthJohri!
> 
> If you have time, if relevant, I'd be interested to hear about any pain points in the process of contributing. For example, could the `CONTRIBUTING` doc be clearer etc, or did you run into any issues setting up the dev environment?
> 
> I'll slightly modify the PR title simply because that it what will appear in the auto generated release notes.
> 
> Thanks again!

No, the `CONTRIBUTING` doc was pretty descriptive, I did come across some issues, for example I was getting some errors with mamba so used conda for setting up the dev environment, and after it, I was able to complete the task without any problems.

**Pull request merged**
