### PR TITLE
improve math rendering of pymc model docs

### PR DESCRIPTION
**Pull request by jpreszler**
This resolves issue #238 
Screenshot 2023-09-16 at 2 25 54 PM

### CODE REVIEW

**Comment by drbenvincent** [comment]
Not sure why the doctests are failing - they pass when I run then locally. Sometimes remote tests randomly fail and then pass when they are re-run, but that hasn't worked here (yet).

**Comment by jpreszler** [comment]
@drbenvincent The failure is coming from numpy when conftest is getting initialized, looks like it's the same issue on your website change pr. A new version was just released and the may have changed something. I've pinned version 1.24.4 (the most recent that github has before 1.26.0, I had 1.25.2 locally) and the tests are starting to run now.

**Comment by jpreszler** [comment]
The issue is actually coming from https://github.com/pymc-devs/pytensor/blob/main/pytensor/link/c/cmodule.py#L2720 in pytensor. Since CausalyPy and PyTensor don't have upper limits on the numpy version, this line throws an exception since v1.26.0 (released on Sept. 16th) no longer has the `get_info()` method.

**Comment by drbenvincent** [comment]
Cool. I see you've dropped an issue in the pytensor repo https://github.com/pymc-devs/pytensor/issues/441

What do you think the best way forward is? Something like this?
* Temporarily pin `numpy<1.26.0` like you've done **and** create an issue to resolve this in the future. 
* That future resolution would also presumably require a version of pytensor which resolves your issue https://github.com/pymc-devs/pytensor/issues/441 ?

**Pull request merged**
