### PR TITLE
User specified number of significant figures for numbers in plots

### LINKED ISSUE #266: add a `round_to` kwarg in all the plot methods
Right now the `plot` methods report numerical results with a hard-wired number of decimal places. The user should be able to specify this. Add a `round_to` (inspired by [what arviz uses](https://python.arviz.org/en/stable/_modules/arviz/plots/posteriorplot.html?highlight=round_to#)) kwarg to all the plot methods to achieve this.

- [x] Add the round_to kwarg and associated utility functions
- [x] The docstrings will need to be updated. 
- [x] Add tests to cover the new functions

### PR DESCRIPTION
**Pull request by drbenvincent**
Closes #266.

The core functions (`round_num` and `_format_sig_figs`) are taken from the Arviz repo.

Tests are included.

I've re-run selected notebooks

### CODE REVIEW

**Comment by juanitorduz** [comment]
LGTM but there is a doc-test failing ¯\\_(ツ)_/¯

**Comment by drbenvincent** [comment]
Remote failing tests should hopefully be fixed whenever https://github.com/pymc-devs/pytensor/pull/550 is fixed and make its way into a new pytensor release. Or when https://github.com/pymc-labs/CausalPy/issues/279 is resolved. So don't sink any effort into trying to fix failing remote tests right now. You can of course ensure that all local tests pass - they are not affected by the issue. Not on my machine anyway.

**Comment by drbenvincent** [comment]
Well this is frustrating. Remote tests still not passing.

**Comment by drbenvincent** [comment]
I'd appreciate any input from @jpreszler or @juanitorduz on the failing test here. I think (at least a while ago) there are two issues. One is a failing doctest for `PrePostNEGD`, but I edited the docstring and my local doctests (and tests) pass. The other is failing remote tests for a different reason (see https://github.com/pymc-labs/CausalPy/issues/279). As far as I can tell it's still the failing doctest that is the issue. But because mine passes locally, I'm not really sure how to proceed. Any input is much appreciated.

**Comment by drbenvincent** [comment]
Oh, I think it's because the results differ on each run when reported at 2 decimal places. I'll enable the `round_to` kwarg for the `summary` method as well.

**Pull request merged**
