### PR TITLE
Basic Ci/CD and fix code style

### PR DESCRIPTION
**Pull request by juanitorduz**
Partially closes https://github.com/pymc-labs/CausalPy/issues/57

This PR:
- [x] Add Makefile
- [x] Add lint and tests requirements
- [x] Add dummy test folder / file
- [x] Fix style (black + flake8 + isort) of the whole code base. 

@drbenvincent, please double-check the small changes I had to do to fix the style. Feel free to push changes to the branch. I tried to change the least as possible.

Note that the tests and lint are passing on my fork: https://github.com/juanitorduz/CausalPy/actions/runs/3517816662/jobs/5896022154

### CODE REVIEW

**Comment by juanitorduz** [comment]
The lint check  detected a duplicated name
```
/causalpy/data/simulate_data.py:101:1: F811 redefinition of unused 'generate_time_series_data' from line 70
```

**Comment by drbenvincent** [comment]
These are the only instances of `generate_time_series_data` in the repo and one of them is in the docstring, so a little confusing. 
Screenshot 2022-11-23 at 20 38 44

**Comment by juanitorduz** [comment]
Ok! Thanks for checking! It might be I messed up something when resolving conflicts. I'll take a look 🙈

**Comment by juanitorduz** [comment]
But in line 66 you also have a generate_timeseries_data function right? (Same name ?)

**Comment by drbenvincent** [comment]
I'm not sure what's going on. From a search I only got 2 hits. But yes, I see now. Maybe just too much coding for one day!

**Comment by drbenvincent** [comment]
Do we need to add the generated `.coverage` to `.gitignore`?

**Review by drbenvincent — COMMENTED** [review]
I've checked all this over and run the pre-commit checks locally, and the various make commands. Made one commit a moment ago to fix a duplicated function definition. Everything seems fine at this point.

I _think_ you must have merged main into this branch after my updates on Wed evening, but if you can just confirm then I can approve and we can merge.

**Comment by juanitorduz** [comment]
@drbenvincent , in https://github.com/pymc-labs/CausalPy/pull/79/commits/5a74cd89c0dca9ec49a3488f544891164a1a77aa I added some changes which make the version setting easier. Also fixed some missing lint problems. If you see the ci/cd output now is green: https://github.com/juanitorduz/CausalPy/actions/runs/3539004142/jobs/5940424788

Please take a look into it and test locally by running `make init`.

**Pull request merged**
