### PR TITLE
Add tests Model Builder

### PR DESCRIPTION
**Pull request by juanitorduz**
This PR adds some basic test for the model builder class. I also fixed the problem of having mutable structures as default, see for example https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/
I also started adding more strict type hints as I strongly recommend to start using `mypy` for static type checking now as it s still a young project :)

### CODE REVIEW

**Comment by drbenvincent** [comment]
Thanks @juanitorduz, I'll take a proper look at this very soon, but from a quick glance it looks good. 

I was planning on working on #22 soon. So Bambi models will be used for most/all linear model situation. But that won't make `ModelBuilder` defunct - we still want the ability to have custom PyMC models.

And agree with `mypy`, it's on the list (#66) 🙂

**Comment by juanitorduz** [comment]
ok! When you start working in https://github.com/pymc-labs/CausalPy/issues/22, maybe this PR can be used as a initial gide to write test while developing :) I will of course be happy to support with the tests!

**Review by drbenvincent — COMMENTED** [review]
This all looks good. The only thing I don't really follow is what's going on in `causalpy/tests/conftest.py`. Could you just briefly explain, then happy to merge.

**Comment by juanitorduz** [comment]
Sure! The conftest.py file contains global pytest fixtures. In this example rng is a random generator which can be used in all tests and is just defined once. Other use cases to store in this files are toy data as pandas data frames for example. More info https://stackoverflow.com/questions/34466027/in-pytest-what-is-the-use-of-conftest-py-files

**Review by drbenvincent — APPROVED** [review]

**Pull request merged**
